project:
  type: website

website:
  title: " "
  navbar:
    right:
      - about.qmd
      - index.qmd
      - icon: github
        href: https://github.com/peterszykalski
      - icon: linkedin
        href: https://www.linkedin.com/in/peterszykalski/
#      - icon: mastodon
#        href: https://mastodon.com
format:
  html:
    theme:
      - cosmo
      - custom.scss
filters:
   - lightbox 

